# =========================================
# NOMBRE DE LA APLICACIÓN
# =========================================

spring.application.name=moises


# =========================================
# BASE DE DATOS MYSQL
# LOCAL POR DEFECTO / AIVEN CON VARIABLES
# =========================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/portafolio_moises?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================
# HIKARI - POOL DE CONEXIONES
# =========================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000

spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=120000


# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# =========================================
# CONFIGURACIÓN DE VISTAS JSP
# =========================================

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


# =========================================
# SUBIDA DE ARCHIVOS
# =========================================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# =========================================
# CLOUDINARY
# =========================================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# =========================================
# SERVIDOR
# =========================================

server.port=${PORT:8080}


# =========================================
# SESIÓN
# =========================================

server.servlet.session.timeout=60m